#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Groups visitors by IP and HTTP status code.
#   Displays the number of occurrences, IP, and HTTP status
#+  code of each log, in sorted order.
# 
# awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
# 
# ps -aux | grep bash

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
