#!/usr/bin/env bash
# Displays a list of currently running processes.
#   Shows all processes, for all users, including those which might not have a TTY
#   Display in a user-oriented format
#   Show process hierarchy

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
